<?php
/**
 * @category  ParkAndFinch
 * @package   ParkAndFinch_ReCaptcha
 * @author    Nicholas Leduc <nicholas@parkandfinch.com>
 * @copyright 2019 Park and Finch
 * @license   https://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @link      https://www.parkandfinch.com/
 */
?>

<?php
/**
 * @var $this ParkAndFinch_ReCaptcha_Block_Recaptcha
 */
?>

<?php if ($this->isReCaptchaEnabled()): ?>
<p id="recaptcha-branding">This site is protected by reCAPTCHA and the Google
    <a href="https://policies.google.com/privacy">Privacy Policy</a> and
    <a href="https://policies.google.com/terms">Terms of Service</a> apply.
</p>
<?php endif; ?>