<?php
/**
 * @category  ParkAndFinch
 * @package   ParkAndFinch_ReCaptcha
 * @author    Nicholas Leduc <nicholas@parkandfinch.com>
 * @copyright 2019 Park and Finch
 * @license   https://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @link      https://www.parkandfinch.com/
 */
?>

<?php
/**
 * @var $this ParkAndFinch_ReCaptcha_Block_Recaptcha
 */
?>

<?php if ($this->isReCaptchaEnabled()): ?>
<div class='<?php echo $this->getReCaptchaClass(); ?>'></div>
<?php endif; ?>